Ring buffer PR 1
seahorn/verify-c-common pull request #111
Opened 2021-10-26 04:16 UTC by achenchen1

2021-11-01 22:04 UTC, achenchen1 commented
Looks like the first test passed - should I squash commits + copy back the modified jobs from temp into jobs2 for diffing?

2021-11-02 14:47 UTC, priyasiddharth commented
Yes please squash commits.

2021-11-02 15:26 UTC, priyasiddharth commented on seahorn/tmp/ring_buffer_release2/sea.yaml
> +  horn-bv2-tracking-mem: true
add newline please.

2021-11-03 02:34 UTC, priyasiddharth requested changes
We need to think more about how to port ring buffer checks. I've added some comments. Please get back if questions are unclear

2021-11-03 02:34 UTC, priyasiddharth commented on seahorn/jobs2/ring_buffer_acquire2/aws_ring_buffer_acquire_harness2.c
> +  sassert(!sea_is_modified((char *)ring_buf.allocator));
This is incorrect. The original check asserts that the pointer in `allocator` is unchanged. Here we are asserting that the memory pointed to by `allocator` is unchanged.

Ditto for the checks in lines 85, 86

2021-11-03 02:34 UTC, priyasiddharth commented on seahorn/jobs2/ring_buffer_acquire2/aws_ring_buffer_acquire_harness2.c
> +    sassert(!sea_is_modified((char *)ring_buf.allocator) &&
Can you provide some intuition for why `ring_buffers_are_equal` and this `sassert` are equivalent?

To me it seems like we want to check that `allocation` is unmodified and the rest of the equality checks remain.

2021-11-03 02:34 UTC, priyasiddharth commented on seahorn/jobs2/ring_buffer_buf_belongs_to_pool2/aws_ring_buffer_buf_belongs_to_pool_harness2.c
> +  sassert(!sea_is_modified((char *)&ring_buf));
This replacement of `ring_buffers_are_equal` is different from `aws_ring_buffer_acquire_up_to_harness2.c` ... why so?

2021-12-01 19:15 UTC, priyasiddharth commented
This looks good to be merged. Please resolve outdated comment and fix the one new comment and I can merge it.

2021-12-11 22:23 UTC, priyasiddharth commented
note to self:
I will merge this once tests pass

2021-12-11 22:35 UTC, priyasiddharth commented
This CI has passed before a trivial change was made so assuming the risk and merging it in.

2021-12-11 22:36 UTC, merged