Sea tracking
seahorn/verify-c-common pull request #112
Opened 2021-10-29 04:31 UTC by liam-metke

All harnesses in the jobs2 directory are directly copied from the jobs directory, but the names are changed to reflect the jobs2 naming scheme. Note all the sea.yaml files and CMakeLists.txt files are configured for the jobs2 variant of the harness.

2021-11-01 13:55 UTC, priyasiddharth requested changes

2021-11-01 13:55 UTC, priyasiddharth commented on seahorn/jobs2/byte_buf_eq_ignore_case2/CMakeLists.txt
> +sea_add_smack(byte_buf_eq_ignore_case2 ${AWS_C_COMMON_ROOT}/source/byte_buf.c
This test should be applied to smack since it uses seahorn primitives

2021-11-01 13:57 UTC, priyasiddharth requested changes

2021-11-01 13:57 UTC, priyasiddharth commented on seahorn/jobs2/byte_buf_eq_ignore_case2/CMakeLists.txt
> +# fuzz
remove fuzz also. Not needed.

2021-11-01 13:57 UTC, priyasiddharth commented on seahorn/jobs2/array_eq_c_str2/CMakeLists.txt
> +sea_add_fuzz(array_eq_c_str2
remove fuzz -- not needed

2021-11-01 13:57 UTC, priyasiddharth commented on seahorn/jobs2/byte_buf_eq_c_str2/CMakeLists.txt
> +sea_add_fuzz(byte_buf_eq_c_str2
remove fuzz

2021-11-03 00:12 UTC, liam-metke commented on seahorn/jobs2/byte_buf_eq_ignore_case2/CMakeLists.txt
> +# fuzz
Removed fuzz

2021-11-03 00:13 UTC, liam-metke commented on seahorn/jobs2/byte_buf_eq_c_str2/CMakeLists.txt
> +sea_add_fuzz(byte_buf_eq_c_str2
Removed fuzz

2021-11-03 00:13 UTC, liam-metke commented on seahorn/jobs2/array_eq_c_str2/CMakeLists.txt
> +sea_add_fuzz(array_eq_c_str2
Removed fuzz

2021-11-03 02:13 UTC, priyasiddharth commented
I am accepting the PR since the failing test has not been touched and I believe it is flaky.

2021-11-03 02:14 UTC, merged