fix: updated LLVM version in README
seahorn/verify-c-common pull request #141
Opened 2023-05-12 15:24 UTC by BorisJancicUWaterloo

Set main version of LLVM to 14
Noted that KLEE uses LLVM 11, SMACK uses 12, Symbiotic uses 10

2023-05-12 15:28 UTC, agurfinkel requested changes
I think there is a typo in symbiotic description

2023-05-12 15:28 UTC, agurfinkel commented on README.md
> +Make sure to use the correct version of LLVM and seahorn when using SMACK
smack? typo?

2023-05-12 18:18 UTC, agurfinkel commented
@BorisJancicUWaterloo is this ready or still WIP?

2023-05-26 21:50 UTC, BorisJancicUWaterloo commented
Yes it is ready

2023-05-27 01:30 UTC, agurfinkel approved these changes

2023-05-27 01:30 UTC, merged